#### install spark-xml plug in in maven -repository - spark-xml (com.databricks)

* 1) goto=>Cluster Libraries => Instal New 
* 2) Maven => Search in coordinates
* 3) Select Maven Cental & Search "spark.xml"
* 4) Select com.databricks - spark-xml_2.12
* 5) Install


And also its working for below Spark & Scala Version. Its not working for Spark 2x version.

7.1 (includes Apache Spark 3.0.0, Scala 2.12)

#### Reading XML file we have to set below parameters in options.

* `path`: Location xml  files.

* `rowTag`: The row tag of your xml files to treat as a row. For example, in this xml ..., the appropriate value would be book. Default is ROW.
* `rootTag`: The root tag of your xml files to treat as the root. For example, in this xml ..., the appropriate value would be books. Default is ROWS.

* `df=spark.read.format("com.databricks.spark.xml").option("rootTag", "emp").option("rowTag","row").load("/FileStore/tables/emp_xml.xml")`
#### When writing files the API accepts several options:

* `path`: Location to write files.
* `rowTag`: The row tag of your xml files to treat as a row. For example, in this xml <books> <book><book> ...</books>, the appropriate value would be book. Default is ROW.
* `rootTag`: The root tag of your xml files to treat as the root. For example, in this xml <books> <book><book> ...</books>, the appropriate value would be books. Default is ROWS.
* `nullValue`: The value to write null value. Default is string null. When this is null, it does not write attributes and elements for fields.
* `attributePrefix`: The prefix for attributes so that we can differentiating attributes and elements. This will be the prefix for field names. Default is _.
* `valueTag`: The tag used for the value when there are attributes in the element having no child. Default is _VALUE.
* `compression`: compression codec to use when saving to file. Should be the fully qualified name of a class implementing org.apache.hadoop.io.compress.CompressionCodec or one of case-insensitive shorten names (bzip2, gzip, lz4, and snappy). Defaults to no compression when a codec is not specified.
* Currently it supports the shortened name usage. You can use just `xml` instead of `com.databricks.spark.xml`.

* Defining Custom Schema for source file...

In [4]:
from pyspark.sql.types import *
customSchema = StructType([ \
    StructField("COMM", StringType(), True), \
    StructField("DEPTNO", StringType(), True), \
    StructField("EMPNO", StringType(), True), \
    StructField("ENAME", StringType(), True), \
    StructField("HIREDATE", StringType(), True), \
    StructField("JOB", StringType(), True), \
    StructField("MGR", StringType(), True), \
    StructField("SAL", StringType(), True)])

In [5]:
customSchema

In [6]:
!pip /usr/bin/spark-shell   --packages com.databricks:spark-xml_2.12:0.9.0

* Reading Xml File from databricks storage location using  `com.databricks.spark.xml`  or `xml`

In [8]:
%fs ls /FileStore/tables/emp_xml.xml

path,name,size
dbfs:/FileStore/tables/emp_xml.xml,emp_xml.xml,3207

In [9]:
df=spark.read.text("/FileStore/tables/emp_xml.xml")

In [10]:
display(df)

value
"<?xml version=""1.0"" encoding=""UTF-8"" ?>"
""
""
7369
SMITH
CLERK
7902
17-12-80
800
""
20
""
""
7499
ALLEN
SALESMAN
7698
20-02-81
1600
300
30
""
""
7521
WARD
SALESMAN
7698
22-02-81
1250
500
30
""
""
7566
JONES
MANAGER
7839
02-04-81
2975
""
20
""
""
7654
MARTIN
SALESMAN
7698
28-09-81
1250
1400
30
""
""
7698
SGR
MANAGER
7839
01-05-81
2850
""
30
""
""
7782
RAVI
MANAGER
7839
09-06-81
2450
""
10
""
""
7788
SCOTT
ANALYST
7566
19-04-87
3000
""
20
""
""
7839
KING
PRESIDENT
""
17-11-81
5000
""
10
""
""
7844
TURNER
SALESMAN
7698
08-09-81
1500
0
30
""
""
7876
ADAMS
CLERK
7788
23-05-87
1100
""
20
""
""
7900
JAMES
CLERK
7698
03-12-81
950
""
30
""
""
7902
FORD
ANALYST
7566
03-12-81
3000
""
20
""
""
7934
MILLER
CLERK
7782
23-01-82
1300
""
10
""
""
1234
SEKHAR
doctor
7777
""
667
78
80
""
""

In [11]:
df=spark.read.format("com.databricks.spark.xml").option("rootTag", "emp").option("rowTag","row").load("/FileStore/tables/emp_xml.xml")

In [12]:
df.printSchema()

In [13]:
display(df)

COMM,DEPTNO,EMPNO,ENAME,HIREDATE,JOB,MGR,SAL
null,20,7369,SMITH,17-12-80,CLERK,7902,800
300,30,7499,ALLEN,20-02-81,SALESMAN,7698,1600
500,30,7521,WARD,22-02-81,SALESMAN,7698,1250
null,20,7566,JONES,02-04-81,MANAGER,7839,2975
1400,30,7654,MARTIN,28-09-81,SALESMAN,7698,1250
null,30,7698,SGR,01-05-81,MANAGER,7839,2850
null,10,7782,RAVI,09-06-81,MANAGER,7839,2450
null,20,7788,SCOTT,19-04-87,ANALYST,7566,3000
null,10,7839,KING,17-11-81,PRESIDENT,null,5000
0,30,7844,TURNER,08-09-81,SALESMAN,7698,1500
null,20,7876,ADAMS,23-05-87,CLERK,7788,1100
null,30,7900,JAMES,03-12-81,CLERK,7698,950
null,20,7902,FORD,03-12-81,ANALYST,7566,3000
null,10,7934,MILLER,23-01-82,CLERK,7782,1300
78,80,1234,SEKHAR,,doctor,7777,667

In [14]:
emp_df = spark.read.format('xml').option("rootTag", "emp").option("rowTag","row").load('/FileStore/tables/emp_xml.xml',schema=customSchema)

In [15]:
display(emp_df)

COMM,DEPTNO,EMPNO,ENAME,HIREDATE,JOB,MGR,SAL
,20,7369,SMITH,17-12-80,CLERK,7902,800
300,30,7499,ALLEN,20-02-81,SALESMAN,7698,1600
500,30,7521,WARD,22-02-81,SALESMAN,7698,1250
,20,7566,JONES,02-04-81,MANAGER,7839,2975
1400,30,7654,MARTIN,28-09-81,SALESMAN,7698,1250
,30,7698,SGR,01-05-81,MANAGER,7839,2850
,10,7782,RAVI,09-06-81,MANAGER,7839,2450
,20,7788,SCOTT,19-04-87,ANALYST,7566,3000
,10,7839,KING,17-11-81,PRESIDENT,,5000
0,30,7844,TURNER,08-09-81,SALESMAN,7698,1500
,20,7876,ADAMS,23-05-87,CLERK,7788,1100
,30,7900,JAMES,03-12-81,CLERK,7698,950
,20,7902,FORD,03-12-81,ANALYST,7566,3000
,10,7934,MILLER,23-01-82,CLERK,7782,1300
78,80,1234,SEKHAR,,doctor,7777,667

In [16]:
display(df)

COMM,DEPTNO,EMPNO,ENAME,HIREDATE,JOB,MGR,SAL
,20,7369,SMITH,17-12-80,CLERK,7902,800
300,30,7499,ALLEN,20-02-81,SALESMAN,7698,1600
500,30,7521,WARD,22-02-81,SALESMAN,7698,1250
,20,7566,JONES,02-04-81,MANAGER,7839,2975
1400,30,7654,MARTIN,28-09-81,SALESMAN,7698,1250
,30,7698,SGR,01-05-81,MANAGER,7839,2850
,10,7782,RAVI,09-06-81,MANAGER,7839,2450
,20,7788,SCOTT,19-04-87,ANALYST,7566,3000
,10,7839,KING,17-11-81,PRESIDENT,,5000
0,30,7844,TURNER,08-09-81,SALESMAN,7698,1500
,20,7876,ADAMS,23-05-87,CLERK,7788,1100
,30,7900,JAMES,03-12-81,CLERK,7698,950
,20,7902,FORD,03-12-81,ANALYST,7566,3000
,10,7934,MILLER,23-01-82,CLERK,7782,1300
78,80,1234,SEKHAR,,doctor,7777,667

*  Writing (Saving data into XML) using `xml`  or `com.databricks.spark.xml` with options  `rootTag` and `rowTag`

In [18]:
emp_df.select("*").write.format('com.databricks.spark.xml').option("rootTag","emp").option("rowTag","row").save('/FileStore/tables/5xml',mode="overwrite")

In [19]:
%fs
ls /FileStore/tables/5xml/

path,name,size
dbfs:/FileStore/tables/5xml/_SUCCESS,_SUCCESS,0
dbfs:/FileStore/tables/5xml/part-00000,part-00000,3636

import os
os.environ['PYSPARK_SUBMIT_ARGS'] = ' --packages com.databricks:spark-xml_2.11.12:0.6.0 pyspark-shell'